name: Train and Build

on:
  push:
    branches:
      - main  # Trigger on pushes to main
  workflow_dispatch:  # Enable manual triggering

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Match your Python version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train model
        run: python train.py  # This will create your model and vectorizer pickle files

      - name: Build the Docker image
        run: docker build -t 575390496000.dkr.ecr.us-east-1.amazonaws.com/my-nlp-repo:latest .

      - name: Configure AWS credentials
        uses: actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::575390496000:role/github-actions-ecr-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push the Docker image to ECR
        run: docker push 575390496000.dkr.ecr.us-east-1.amazonaws.com/my-nlp-repo