name: Train and Build

on:
  push:
    branches:
      - main  # Trigger on pushes to main
  workflow_dispatch:  # Enable manual triggering

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Match your Python version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train model
        run: python train.py  # This will create your model and vectorizer pickle files

      - name: Build Docker image
        run: docker build -t bhpac/modellifecycleaws:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push bhpac/modellifecycleaws:${{ github.sha }}